db.createCollection('info');


db.info.insertMany([
    { title: "My Name Is Gabibbo", label: "EMI Italiana", year: 1991, type: "musica" },
    { title: "Un attimino", label: "Five", year: 1995, type: "musica" },
    { title: "Fu Fu Dance", label: "Five", year: 1996, type: "musica" },
    { title: "Ti spacco la faccia", label: "EMI Italiana", year: 1990, type: "musica" },
    { title: "Ma sei scemo!?", label: "Five", year: 1991, type: "musica" },
    { title: "Veline - Striscia la Compilation", label: "Universal Music Group", year: 2008, type: "musica" },
    { title: "Striscia la notizia", tv_channel: "Canale 5", year: 1990, type: "tv" },
    { title: "Striscia 90...la notizia canta", tv_channel: "Canale 5", year: 1990, type: "tv" },
    { title: "Paperissima Sprint", tv_channel: "Italia 1", year: 1990, type: "tv" },
    { title: "Paperissima", tv_channel: "Canale 5", year: 1992, type: "tv" },
    { title: "Natale in casa Gabibbo", tv_channel: "Italia 1", year: 1991, type: "tv" },
    { title: "Nuovo Cinema Gabibbo", tv_channel: "Italia 1", year: 1991, type: "tv" },
    { title: "Mondo Gabibbo", tv_channel: "Canale 5", year: 1992, type: "tv" },
    { title: "Estatissima Sprint", tv_channel: "Canale 5", year: 1996, type: "tv" },
    { title: "Doppio lustro", tv_channel: "Canale 5", year: 1998, type: "tv" },
    { title: "Striscia di mezza sera", tv_channel: "Canale 5", year: 1999, type: "tv" },
    { title: "Allegria!", tv_channel: "Canale 5", year: 1999, type: "tv" },
    { title: "Striscina la notizina", tv_channel: "Canale 5", year: 1999, type: "tv" },
    { title: "Veline", tv_channel: "Canale 5", year: 2002, type: "tv" },
    { title: "Velone", tv_channel: "Canale 5", year: 2003, type: "tv" },
    { title: "Cultura moderna", tv_channel: "Canale 5", year: 2006, type: "tv" },
    { title: "Cultura moderna Slurp", tv_channel: "Canale 5", year: 2007, type: "tv" },
    { title: "Paperissima al circo", tv_channel: "Canale 5", year: 2007, type: "tv" },
    { title: "Capodanno con Paperissima", tv_channel: "Canale 5", year: 2007, type: "tv" },
    { title: "Paperissima Pan", tv_channel: "Canale 5", year: 2008, type: "tv" },
    { title: "Striscia la domenica", tv_channel: "Canale 5", year: 2013, type: "tv" },
    { title: "Cucciolo", year: 1998, direction: "Neri Parenti", type: "cinema" },
    { title: "Al momento giusto", year: 2000, direction: "Giorgio Panariello", type: "cinema" },
    { title: "Capitan Basilico 2", year: 2011, direction: "Massimo Morini", type: "cinema" },
    { title: "flag", author: "xato", year: 1337, type: "secret", flag: 'flag{REDACTED}' },
]);